aneurysm:
  t: 0.1 # thickness of wall
  r_art_i: 1.5
  r_ca_i: 3.2
  h_y_ca: 3.5 #distance between centerline and center of aneurysm
  L: 7
  n_ref_surf: 0 # refine surface before extrusion
  n_ref_neck: 0 # refine additional the surface around the anerym neck
time:
  steps1: 100
  steps2: 100
  dt_1: 1
  dt_2: 0.5
